window.TICKET_DRAGON_NAMES = [
  'Skelequeen Dragon', 'Skeleking Dragon', 'Solar Fyre Dragon', 'Lunar Fyre Dragon',
  'Old Klaws Dragon', 'Mama Klaws Dragon', 'Mother Earth Dragon', 'Father Sky Dragon',
  'Forever Dragon', 'Beloved Dragon', 'Orbit Dragon', 'Universe Dragon',
  'Neo Unicorn Dragon', 'Neo Kitsune Dragon', 'White Lotus Dragon', 'Nightflower Dragon',
  'Bright Diamond Dragon', 'Dark Amethyst Dragon', 'Seaqueen Dragon', 'Seaking Dragon',
  'Bluejay Dragon', 'Cardinal Dragon', 'Glitterspark Dragon', 'Conjur Dragon',
  'Nevermore Dragon', 'Dark Leaf Dragon', 'Drake Dragon', 'Scarbolt Dragon',
  'Herald Dragon', 'Choir Dragon', 'Gryffin', 'Unicorn',
  'Peryton', 'Dire Wolf', 'Pegasus', 'Rainbow Queen Dragon',
  'Paeonia Dragon', 'Crux Dragon', 'Chromastripe Dragon', 'Daycast Dragon',
  'Luxor Dragon', 'Occult Dragon', 'Crystal Hearth Dragon', 'Cozy Dragon',
  'Playful New Year Dragon', 'Overlove Dragon', 'Strongshine Dragon', 'Party Star Dragon',
  'Bold Floral Dragon', 'Foolish Dragon', 'Pink Pixie Dragon', 'Reflector Dragon',
  'Showy Dragon', 'Swirl Dragon', 'Pleasantry Dragon', 'Valor Dragon',
  'Gildheart Dragon', 'Stern Dragon', 'Leader Dragon', 'Dayflower Dragon',
  'Averse Dragon', 'Sincere Dragon', 'Elite Champion Dragon', 'Lazuli Dragon',
  'Crest Dragon', 'Brightsky Dragon', 'Sleet Dragon', 'Palebark Dragon',
  'Tune Dragon', 'Bioluminescent Dragon', 'Budding Dragon', 'Paper Flower Dragon',
  'Crystalline Dragon', 'Wind Dragon', 'Wilderness Dragon', 'Skelelady Dragon',
  'Lepus Dragon', 'Rocker Dragon', 'Radiance Dragon', 'Bloom Dragon',
  'Gamut Dragon', 'Loot Dragon', 'Seasteed Dragon', 'Sunset Opal Dragon',
  'Tangle Dragon', 'Frostglow Dragon', 'Trinket Dragon', 'Ancient Star Dragon',
  'Stellar Aurora Dragon', 'Neo Diamond Dragon', 'Neo Rainbow Dragon', 'Neo Black Dragon',
  'Neo Purple Dragon', 'Neo White Dragon', 'Neo Pink Dragon', 'Neo Red Dragon',
  'Neo Green Dragon', 'Neo Blue Dragon', 'Neo Yellow Dragon', 'Royal Specter Dragon',
  'Minerva Dragon', 'Bauble Dragon', 'Spymaster Dragon', 'Spunky Dragon',
  'Gold Horizon Dragon',
];
